### ISSUE TITLE
support reject and cancel order?

### ISSUE THREAD

**Issue by ForrestSu** [embosfer/fixbro#6]
At line 55 "new SessionID("FIX.4.2:SE->BUY1");" I want to get it from  active sessions?  How can I fix it?
Thank you ~ @embosfer

**Comment by embosfer** [comment]
Hi @ForrestSu, now the sessionID is not hardcoded anymore. 
Cheers

**Comment by ForrestSu** [comment]
thank you very much! 
Cheers ^_^
